version: "3"
services:
    php:
        # image: php:8.2.0-fpm
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www
        networks:
            - laravel

    nginx:
        image: nginx:stable
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel

    mysql:
        image: mysql:8.0.31-debian
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
        networks:
            - laravel
        environment:
            MYSQL_DATABASE: training_dekkson
            MYSQL_USER: tester
            MYSQL_PASSWORD: 123
            MYSQL_ROOT_PASSWORD: 123

networks:
    laravel:
